swiftmailer:
    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }

    # à configurer

#    transport:            ~
#    username:             ~
#    password:             ~
#    host:                 localhost
#    port:                 ~
#    encryption:           ~
#    auth_mode:            ~
#    spool:
#        type:                 file
#        path:                 '%kernel.cache_dir%/swiftmailer/spool'
#    sender_address:       ~
#    antiflood:
#        threshold:            99
#        sleep:                0
#    delivery_addresses:   []
#    disable_delivery:     ~
#    logging:              '%kernel.debug%'

