<?php
declare(strict_types=1);

namespace App\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class IsBookingValid extends Constraint
{
    public $pastDay = 'Il n\'est pas possible de commander pour les jours passés.';

    public $closedDay = '"Il n\'est pas possible de commander pour le {{ dateForm }}". Car le musé est fermé.';

    public $notAvailable = 'Vous ne pouvez pas commender de billets pour cette date. Votre commande doit concerner l\'année en cours';

    /**
     * Returns the name of the class that validates this constraint.
     *
     * By default, this is the fully qualified name of the constraint class
     * suffixed with "Validator". You can override this method to change that
     * behaviour.
     *
     * @return string
     */
    public function validatedBy()
    {
        return parent::validatedBy(); // TODO: Change the autogenerated stub
    }
}
